[package]
name = "sonicmux-runtime"
description = "Scheduling and application runtime for SonicMux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
directories.workspace = true
glob.workspace = true
globset.workspace = true
renamore.workspace = true
serde.workspace = true
sonicmux-backend.workspace = true
sonicmux-core.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
walkdir.workspace = true

[dev-dependencies]
async-trait.workspace = true
serde_json.workspace = true
sonicmux-ffmpeg.workspace = true

[lints]
workspace = true
